export { CheckboxSearchBar } from './checkbox-search-bar/checkbox-search-bar.component'
export { ErrorFallback } from './error-fallback/error-fallback.component'
export { Header } from './header/header.component'
export { Loader } from './loader/loader.component'
export { ProductSingleModal as ImageModal } from './modal-image/modal-image.component'
export { SearchBar } from './search-bar/search-bar.component'
export { SelectSearchBar } from './select-search-bar/select-search-bar.component'
export { SliceSentence } from './slice-sentence/slice-sentence.component'
export { ThemeSwitcher } from './theme-switcher/theme-switcher.component'
